---
title: "Atividade1- Checkpoint 4"
author: "Dandara Sousa"
date: "26 de maio de 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.width = 10)
```

```{r include=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(readr)

library(knitr)
```
##Conjunto de Dados
```{r}
series = read.csv("series_from_imdb.csv")

unique(series$series_name)

```


4. Quanto mais antiga uma série é mais bem avaliada ela é?
[contexto: pegar a de menor e a de maior temporadas]
```{r}
series %>% 
  group_by(series_name) %>%
  summarise(numeroTemp = max(season)) %>%
  ggplot(aes(x = series_name, y = numeroTemp)) + 
  geom_bar(stat = "identity", fill = "dark blue") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + labs(x="Nome da série",y="Número de temporadas") + 
  scale_y_continuous(breaks=seq(0, 11, 1)) 
```
[dizer o resultado do gráfico]
[]
```{r}
series_extremas = series %>% filter(series_name %in% c("13 Reasons Why","Stranger Things","Friends","Grey's Anatomy","How I Met Your Mother","The Simpsons"))

series_extremas %>%
  ggplot(aes(x = series_name,y = UserRating, color = series_name)) + geom_boxplot() + 
  labs(title = "Avalição de séries do subconjunto", x= "Nome da Série", y= "Nota do Usuário") + 
  geom_jitter(width = .1, size = 1, alpha = .2) +  
  stat_summary(aes(label=round(..y..,2)), fun.y=median, geom="text", size=4, vjust = -0.5, color = "black") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```




6. Em geral, as notas de uma série crescem de acordo com as temporadas?

```{r}
series_recentes = series %>% filter(series_name %in% c("13 Reasons Why","Agentes of S.H.I.E.L.D","Black Mirror","Daredevil","Flash","Gotham","House of Cards","How to Get Away with Murder","Mr Robot", "Narcos", "Orphan Black", "Prision Break","Sense8","Sherlock","Stranger Things","The 100", "The Blacklist","Vikings"))
series_antigas = series %>% filter(series_name %in% c("13 Reasons Why","Stranger Things","Friends","Grey's Anatomy","How I Met Your Mother","The Simpsons"))
```

```{r}
series_recentes %>%
  group_by(series_name,season) %>%
  summarise(mediana = median(UserRating)) %>%
  ggplot(aes(x = season,y = mediana, color = series_name)) + 
  geom_point(alpha=.8) + 
  geom_line() +
  scale_x_continuous(breaks=seq(0, 11, 1)) +
  scale_y_continuous(breaks=seq(6, 10, .5)) +
  theme(legend.position = "bottom") +
  labs(x = "Temporada",y = "Mediana")
```

```{r}
series_antigas %>%
  group_by(series_name,season) %>%
  summarise(mediana = median(UserRating)) %>%
  ggplot(aes(x = season,y = mediana, color = series_name)) + 
  geom_point(alpha=.8) + 
  geom_line() +
  scale_x_continuous(breaks=seq(0, 11, 1)) +
  scale_y_continuous(breaks=seq(6, 10, .5)) +
  theme(legend.position = "bottom") +
  labs(x = "Temporada",y = "Mediana")
```


